name: Build and Run BWC Tests

on:
  push:
    branches:
      - "bwc-*"
  pull_request:
    branches:
      - "bwc-*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [21]
    name: Build and Run BWC Tests
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}

      - name: Build and Run Tests
        run: |
          ./gradlew --info bwcTestSuite -Dtests.security.manager=false -x yamlRestTest
